services:
  - type: web
    name: atm-py
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn atm:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
